name: studio_repository
description: Repository for processing studio data
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  db_client:
    path: ../db_client
  hub_domain:
    path: ../../../packages/hub_domain

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
